# Generated by Django 2.2.13 on 2020-06-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CovidObservations',
            fields=[
                ('sno', models.IntegerField(primary_key=True, serialize=False)),
                ('observation_date', models.DateField()),
                ('province_state', models.CharField(max_length=255)),
                ('country_region', models.CharField(max_length=255)),
                ('last_update', models.DateTimeField()),
                ('confirmed', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('recovered', models.IntegerField()),
            ],
            options={
                'db_table': 'covid_observations',
            },
        ),
    ]
